# Generated by Django 4.1 on 2022-08-25 12:47

import datetime
from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=users.models.AutoDateTimeField(default=datetime.date.today),
        ),
    ]
